import Database from "better-sqlite3";
import path from "path";

const dbPath = path.join(process.cwd(), "helmet.db");

declare global {
  var db: Database.Database | undefined;
}

let db = global.db;

if (!db) {
  db = new Database(dbPath);

  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");

  global.db = db;
}

const createProjects = `
CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  status INTEGER DEFAULT 0,
  settings TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch()) 
)
`;

const createImages = `
CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  initial_image_date INTEGER,
  initial_image_location TEXT,
  file_name TEXT NOT NULL,
  thumb_file_name TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch()),
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
)
`;

const createPeople = `
CREATE TABLE IF NOT EXISTS people (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  person_confidence INTEGER NOT NULL,
  helmet_confidence INTEGER NOT NULL,
  has_helmet INTEGER NOT NULL,
  person_box TEXT NOT NULL,
  helmet_box TEXT,
  created_at INTEGER DEFAULT (unixepoch()),
  FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
)
`;

db.exec(createProjects);
db.exec(createImages);
db.exec(createPeople);

export default db;

/**
 * Creates a new project in the database.
 *
 * @param name - The project name generated by generateProjectName
 * @param settings - The project settings object
 * @returns The ID of the created project or null if failed
 */
export function createProject(name: string, settings: object): number | null {
  try {
    const stmt = db.prepare(`
      INSERT INTO projects (name, user_id, status, settings, created_at)
      VALUES (?, ?, ?, ?, ?)
    `);

    const result = stmt.run(
      name,
      0, // user_id for future role model
      0, // status: 0 - not started
      JSON.stringify(settings),
      Math.floor(Date.now() / 1000) // current timestamp in seconds
    );

    return result.lastInsertRowid as number;
  } catch (error) {
    console.error("Failed to create project:", error);
    return null;
  }
}

/**
 * Creates a new image record in the database.
 *
 * @param projectId - The ID of the project
 * @param initialImageDate - The initial date of the image (optional)
 * @param initialImageLocation - The initial location of the image (optional)
 * @param fileName - The file name of the saved image
 * @param thumbFileName - The file name of the saved thumbnail
 * @returns The image object or null if failed
 */
export function createImage(
  projectId: number,
  initialImageDate: number | null,
  initialImageLocation: string | null,
  fileName: string,
  thumbFileName: string
): {
  id: number;
  projectID: number;
  initialImageDate: number | null;
  initialImageLocation: string | null;
  fileName: string;
  thumbFileName: string;
  createdAt: number;
} | null {
  try {
    const createdAt = Math.floor(Date.now() / 1000);
    const stmt = db.prepare(`
      INSERT INTO images (project_id, initial_image_date, initial_image_location, file_name, thumb_file_name, created_at)
      VALUES (?, ?, ?, ?, ?, ?)
    `);

    const result = stmt.run(
      projectId,
      initialImageDate,
      initialImageLocation,
      fileName,
      thumbFileName,
      createdAt
    );

    return {
      id: result.lastInsertRowid as number,
      projectID: projectId,
      initialImageDate,
      initialImageLocation,
      fileName,
      thumbFileName,
      createdAt,
    };
  } catch (error) {
    console.error("Failed to create image:", error);
    return null;
  }
}

/**
 * Creates a new person record in the database.
 *
 * @param imageId - The ID of the image
 * @param personID - The ID of the person detected
 * @param personConfidence - The confidence score for person detection
 * @param helmetConfidence - The confidence score for helmet detection
 * @param hasHelmet - Whether the person has a helmet
 * @param personBox - Array of coordinates for person bounding box
 * @param helmetBox - Array of coordinates for helmet bounding box (optional)
 * @returns The person object or null if failed
 */
export function createPerson(
  imageId: number,
  personID: number,
  personConfidence: number,
  helmetConfidence: number,
  hasHelmet: boolean,
  personBox: number[],
  helmetBox: number[] | null
): {
  id: number;
  imageID: number;
  personID: number;
  personConfidence: number;
  helmetConfidence: number;
  hasHelmet: boolean;
  personBox: number[];
  helmetBox: number[] | null;
  createdAt: number;
} | null {
  try {
    const createdAt = Math.floor(Date.now() / 1000);
    const stmt = db.prepare(`
      INSERT INTO people (image_id, person_id, person_confidence, helmet_confidence, has_helmet, person_box, helmet_box, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);

    const result = stmt.run(
      imageId,
      personID,
      personConfidence,
      helmetConfidence,
      hasHelmet ? 1 : 0,
      JSON.stringify(personBox),
      helmetBox ? JSON.stringify(helmetBox) : null,
      createdAt
    );

    return {
      id: result.lastInsertRowid as number,
      imageID: imageId,
      personID,
      personConfidence,
      helmetConfidence,
      hasHelmet,
      personBox,
      helmetBox,
      createdAt,
    };
  } catch (error) {
    console.error("Failed to create person:", error);
    return null;
  }
}
